# -*- coding: utf-8 -*-
"""Marmara_Veri_Analizi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkH05sHfCYXg2qlW1Z0KtzcDsT_B-Ux6

# 🌊 Marmara Denizi — Çoklu Platform Veri Analizi

**Veri Kaynakları:**

| Platform | Tip | Veriler | Limit |
|----------|-----|---------|-------|
| Open-Meteo | Ücretsiz | Rüzgar, basınç, 4 model | Sınırsız |
| MET Norway | Ücretsiz | Dalga, SST, akıntı | Sınırsız |
| NASA CoastWatch ERDDAP | Ücretsiz | Klorofil-a VIIRS | Sınırsız |
| Stormglass.io | Freemium | Su sıcaklığı, tuzluluk, oksijen | 10 istek/gün |
| CMEMS Copernicus | Ücretsiz (kayıt) | Klorofil, SST, akıntı | Sınırsız |
| Global Fishing Watch | Ücretsiz (API key) | Balıkçı yoğunluğu | Sınırsız |

**Görselleştirmeler:**
- 📈 Çok-model rüzgar + dalga karşılaştırması (7 günlük)
- 🌿 Klorofil-a uydu haritası (Marmara, yeşil tonu)
- 💨 Rüzgar vektör haritası (matplotlib quiver)
- 📉 Basınç izobar + hava sistemi tespiti
- 🌡️ Oşinografik zaman serisi (SST, tuzluluk, oksijen)
- 🎣 Onshore rüzgar analizi (kıyıya dik — levrek koşulu)

## 📦 1. Kurulum
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install requests numpy pandas matplotlib scipy plotly folium copernicusmarine -q
# print('✅ Kurulum tamamlandı')

"""## 📚 2. İmportlar ve Konfigürasyon"""

import requests, datetime, math, warnings, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.ticker as mticker
from matplotlib.patches import FancyArrowPatch
from matplotlib.gridspec import GridSpec
from scipy.interpolate import griddata
from scipy.ndimage import gaussian_filter
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
warnings.filterwarnings('ignore')

# ── Stil ──────────────────────────────────────────────────────────
plt.rcParams.update({
    'figure.facecolor': '#0a1628',
    'axes.facecolor':   '#0d1e35',
    'axes.edgecolor':   '#1e3a5f',
    'axes.labelcolor':  '#94b8d4',
    'text.color':       '#dff1ff',
    'xtick.color':      '#5a7a96',
    'ytick.color':      '#5a7a96',
    'grid.color':       '#1e3a5f',
    'grid.alpha':       0.5,
    'font.family':      'monospace',
})

# ── API Anahtarları ───────────────────────────────────────────────
STORMGLASS_KEY = 'BURAYA_STORMGLASS_KEY_YAZ'  # https://stormglass.io
CMEMS_USER     = ''  # https://marine.copernicus.eu/register (ücretsiz)
CMEMS_PASS     = ''
GFW_TOKEN      = ''  # https://globalfishingwatch.org/data/open-apis/

# ── Merkez konum (Marmara ortası) ────────────────────────────────
LAT, LON = 40.65, 28.30
print('✅ Hazır')

"""## 📍 3. Analiz Noktaları"""

# Temsili 10 mera — farklı bölgelerden
SPOTS = {
    'İstanbul Avrupa':   {'lat':40.96,'lon':28.84,'shore_facing':180},
    'İstanbul Anadolu':  {'lat':40.91,'lon':29.16,'shore_facing':180},
    'Tekirdağ':          {'lat':40.97,'lon':27.51,'shore_facing':135},
    'Gemlik':            {'lat':40.43,'lon':29.15,'shore_facing':350},
    'Mudanya':           {'lat':40.37,'lon':28.88,'shore_facing':0},
    'Yalova':            {'lat':40.65,'lon':29.27,'shore_facing':0},
    'Bandırma':          {'lat':40.35,'lon':27.97,'shore_facing':30},
    'Erdek':             {'lat':40.39,'lon':27.80,'shore_facing':315},
    'Marmara Adası':     {'lat':40.64,'lon':27.54,'shore_facing':0},
    'Şarköy':            {'lat':40.61,'lon':27.11,'shore_facing':135},
}

MODELS = [
    ('icon_d2',      'ICON-D2',  '2km',  '#38bdf8'),
    ('icon_eu',      'ICON-EU',  '7km',  '#2dd4bf'),
    ('ecmwf_ifs04',  'ECMWF',    '9km',  '#a78bfa'),
    ('gfs_seamless', 'GFS',      '25km', '#fbbf24'),
]
print(f'📍 {len(SPOTS)} analiz noktası hazır')

"""## 🌬️ 4. Open-Meteo — Çok-Model Rüzgar (7 Gün)"""

from concurrent.futures import ThreadPoolExecutor

def fetch_openmeteo(lat, lon, model_key):
    try:
        r = requests.get('https://api.open-meteo.com/v1/forecast', params={
            'latitude': lat, 'longitude': lon,
            'hourly': 'windspeed_10m,winddirection_10m,windgusts_10m,surface_pressure',
            'models': model_key,
            'windspeed_unit': 'kmh',
            'timezone': 'Europe/Istanbul',
            'forecast_days': 7
        }, timeout=10)
        if r.ok: return r.json()
    except: pass
    return {}

def fetch_metno_ocean(lat, lon):
    """MET Norway Oceanforecast — dalga, SST, akıntı (ücretsiz)"""
    try:
        r = requests.get(
            'https://api.met.no/weatherapi/oceanforecast/2.0/complete',
            params={'lat': round(lat,3), 'lon': round(lon,3)},
            headers={'User-Agent': 'MarmAv-Analysis/1.0 (research)'},
            timeout=10
        )
        if r.ok:
            ts = r.json().get('properties',{}).get('timeseries',[])
            rows = []
            for t in ts[:168]:  # 7 gün
                det = t.get('data',{}).get('instant',{}).get('details',{})
                rows.append({
                    'time':         t['time'],
                    'wave_height':  det.get('sea_surface_wave_height'),
                    'wave_dir':     det.get('sea_surface_wave_from_direction'),
                    'wave_period':  det.get('sea_surface_wave_mean_period'),
                    'sst':          det.get('sea_water_temperature'),
                    'current_spd':  det.get('sea_water_speed'),
                    'current_dir':  det.get('sea_water_to_direction'),
                })
            df = pd.DataFrame(rows)
            df['time'] = pd.to_datetime(df['time'])
            return df
    except: pass
    return pd.DataFrame()

def fetch_marine(lat, lon):
    try:
        r = requests.get('https://marine-api.open-meteo.com/v1/marine', params={
            'latitude': lat, 'longitude': lon,
            'hourly': 'wave_height,wave_period,swell_wave_height',
            'timezone': 'Europe/Istanbul', 'forecast_days': 7
        }, timeout=10)
        if r.ok: return r.json()
    except: pass
    return {}

# Merkez için tüm modeller
print('📡 Veriler çekiliyor...')
meteo_data = {}
with ThreadPoolExecutor(max_workers=4) as ex:
    futs = {ex.submit(fetch_openmeteo, LAT, LON, k): (k,n,r,c) for k,n,r,c in MODELS}
    for fut, (k,n,res,col) in futs.items():
        d = fut.result()
        if d.get('hourly'):
            meteo_data[n] = {'data': d, 'res': res, 'color': col}
            print(f'  ✅ {n} ({res})')

# Marine
marine_data = fetch_marine(LAT, LON)
print(f'  ✅ Open-Meteo Marine')

# MET Norway
mn_df = fetch_metno_ocean(LAT, LON)
print(f'  ✅ MET Norway ({len(mn_df)} satır)')
print('Tamamlandı!')

"""## 📊 5. Çok-Model Rüzgar Karşılaştırması"""

fig, axes = plt.subplots(3, 1, figsize=(16, 12),
                           facecolor='#0a1628', sharex=True)
fig.suptitle(f'🌬️ Marmara — Çok-Model Rüzgar Analizi\n'
             f'({LAT:.2f}°K, {LON:.2f}°D)',
             fontsize=14, fontweight='bold', color='#38bdf8', y=0.98)

ax_ws, ax_wd, ax_pr = axes

# ── Rüzgar hızı ──────────────────────────────────────────────
ax_ws.set_title('💨 Rüzgar Hızı (km/h)', color='#94b8d4', pad=8)
ax_ws.set_ylabel('km/h', color='#94b8d4')
ax_ws.axhline(40, color='#f87171', ls='--', lw=1, alpha=0.6, label='Fırtına eşiği')
ax_ws.axhline(15, color='#4ade80', ls=':', lw=1, alpha=0.5, label='Levrek eşiği')
ax_ws.fill_between([], [], [], alpha=0)

for model_name, mdata in meteo_data.items():
    h = mdata['data']['hourly']
    times = pd.to_datetime(h['time'])

    # Handle None values in wind speed and gusts
    wind_df = pd.DataFrame({
        'time': times,
        'ws': h['windspeed_10m']
    }).dropna()

    if not wind_df.empty:
        ax_ws.plot(wind_df['time'], wind_df['ws'], label=f"{model_name} ({mdata['res']})",
                   color=mdata['color'], lw=2, alpha=0.9)

    # ±1σ bantı — ilk model için
    if model_name == 'ICON-D2' and h.get('windgusts_10m'):
        gust_df = pd.DataFrame({
            'time': times,
            'ws': h['windspeed_10m'],
            'wg': h['windgusts_10m']
        }).dropna()
        if not gust_df.empty:
            ax_ws.fill_between(gust_df['time'], gust_df['ws'], gust_df['wg'], alpha=0.12, color=mdata['color'],
                               label='Hamle bandı')

ax_ws.legend(loc='upper right', fontsize=8, framealpha=0.3)
ax_ws.grid(True, alpha=0.3)

# ── Dalga yüksekliği ─────────────────────────────────────────
ax_wd.set_title('🌊 Dalga Yüksekliği (m)', color='#94b8d4', pad=8)
ax_wd.set_ylabel('m', color='#94b8d4')
ax_wd.axhline(2.0, color='#f87171', ls='--', lw=1, alpha=0.6, label='>2m tehlike')
ax_wd.axhline(0.5, color='#4ade80', ls=':', lw=1, alpha=0.5, label='İdeal levrek')

if marine_data.get('hourly'):
    mh = marine_data['hourly']
    mt = pd.to_datetime(mh['time'])
    wh = mh.get('wave_height',[])
    sw = mh.get('swell_wave_height',[])

    # Handle None values for marine data as well
    marine_df = pd.DataFrame({'time': mt, 'wh': wh, 'sw': sw})

    if not marine_df['wh'].dropna().empty:
        ax_wd.plot(marine_df['time'], marine_df['wh'], color='#2dd4bf', lw=2.5, label='Dalga (Open-Meteo Marine)')
    if not marine_df['sw'].dropna().empty:
        ax_wd.plot(marine_df['time'], marine_df['sw'], color='#a78bfa', lw=1.5, ls='--', label='Swell', alpha=0.8)

if not mn_df.empty and 'wave_height' in mn_df.columns:
    # mn_df already handled None values in fetch_metno_ocean function, just ensure no NA values are plotted
    mn_wh_plot = mn_df[['time', 'wave_height']].dropna()
    if not mn_wh_plot.empty:
        ax_wd.plot(mn_wh_plot['time'], mn_wh_plot['wave_height'], color='#fb923c', lw=2,
                   ls='-', label='Dalga (MET Norway)', alpha=0.9)

ax_wd.legend(loc='upper right', fontsize=8, framealpha=0.3)
ax_wd.grid(True, alpha=0.3)

# ── Basınç ───────────────────────────────────────────────────
ax_pr.set_title('📉 Deniz Seviyesi Basıncı (hPa)', color='#94b8d4', pad=8)
ax_pr.set_ylabel('hPa', color='#94b8d4')
ax_pr.axhline(1013, color='#5a7a96', ls='--', lw=1, alpha=0.5, label='Normal (1013 hPa)')
ax_pr.axhspan(950, 1000, alpha=0.07, color='#ef4444', label='Düşük basınç zonu')
ax_pr.axhspan(1020, 1040, alpha=0.07, color='#818cf8', label='Yüksek basınç zonu')

for model_name, mdata in meteo_data.items():
    h = mdata['data']['hourly']
    times = pd.to_datetime(h['time'])

    # Handle None values in pressure
    pressure_df = pd.DataFrame({
        'time': times,
        'pr': h.get('surface_pressure', [])
    }).dropna()

    if not pressure_df.empty:
        ax_pr.plot(pressure_df['time'], pressure_df['pr'], color=mdata['color'], lw=1.5, alpha=0.85,
                   label=model_name)

ax_pr.legend(loc='upper right', fontsize=8, framealpha=0.3)
ax_pr.grid(True, alpha=0.3)

# X ekseni
ax_pr.xaxis.set_major_formatter(plt.matplotlib.dates.DateFormatter('%d/%m %H:00'))
plt.xticks(rotation=35, ha='right', fontsize=8)

for ax in axes:
    for sp in ax.spines.values(): sp.set_edgecolor('#1e3a5f')

plt.tight_layout()
plt.savefig('01_wind_wave_analysis.png', dpi=140, bbox_inches='tight')
plt.show()
print('📊 Grafik kaydedildi: 01_wind_wave_analysis.png')

"""## 🌿 6. Klorofil-a Uzamsal Haritası (Yeşil Bulut)"""

# NASA ERDDAP — tüm noktalar için klorofil verisi
ERDDAP_BASE = 'https://coastwatch.noaa.gov/erddap'
ERDDAP_DS   = 'noaacwNPPVIIRSchlaDaily'

def fetch_chl_point(lat, lon):
    url = (f'{ERDDAP_BASE}/griddap/{ERDDAP_DS}.json'
           f'?chlor_a[(last)][({lat:.3f})][({lon:.3f})]')
    try:
        r = requests.get(url, timeout=10)
        if r.ok:
            rows = r.json().get('table',{}).get('rows',[])
            if rows and rows[0][-1] is not None:
                return float(rows[0][-1])
    except: pass
    return None

# 20-nokta ızgara — Marmara üzerinde
grid_lats = np.linspace(40.4, 41.4, 8)
grid_lons = np.linspace(26.2, 30.1, 12)
glo, gla  = np.meshgrid(grid_lons, grid_lats)

print('🛰️ NASA ERDDAP klorofil verisi çekiliyor (paralel)...')
chl_vals = np.zeros_like(glo) + np.nan

with ThreadPoolExecutor(max_workers=12) as ex:
    futs = {}
    for i in range(gla.shape[0]):
        for j in range(gla.shape[1]):
            futs[ex.submit(fetch_chl_point, gla[i,j], glo[i,j])] = (i,j)
    for fut, (i,j) in futs.items():
        v = fut.result()
        if v is not None and 0 < v < 50:
            chl_vals[i,j] = v

valid = np.sum(~np.isnan(chl_vals))
print(f'  ✅ {valid}/{gla.size} noktadan gerçek veri')

# Proxy: veri gelmezse mevsimsel ortalama kullan
if valid < 5:
    print('  ⚠️ ERDDAP verisi yetersiz — proxy model kullanılıyor')
    for i in range(gla.shape[0]):
        for j in range(gla.shape[1]):
            # Kıyıya yakınlık bazlı proxy
            coast_dist = min(abs(gla[i,j]-41.1), abs(gla[i,j]-40.4),
                            abs(glo[i,j]-27.0), abs(glo[i,j]-29.5))
            chl_vals[i,j] = max(0.3, 2.5 - coast_dist * 1.2 + np.random.uniform(0,0.3))

# NaN → interpolate
if np.any(np.isnan(chl_vals)):
    pts_valid = [(glo[i,j], gla[i,j]) for i in range(gla.shape[0])
                 for j in range(gla.shape[1]) if not np.isnan(chl_vals[i,j])]
    vals_valid = [chl_vals[i,j] for i in range(gla.shape[0])
                  for j in range(gla.shape[1]) if not np.isnan(chl_vals[i,j])]
    if pts_valid:
        chl_interp = griddata(pts_valid, vals_valid, (glo, gla), method='cubic')
        chl_vals = np.where(np.isnan(chl_vals), chl_interp, chl_vals)
    chl_vals = np.where(np.isnan(chl_vals), 0.5, chl_vals)

chl_smooth = gaussian_filter(np.log1p(chl_vals), sigma=1.0)
print('✅ Klorofil ızgarası hazır')

# ── Klorofil haritası — yeşil bulut görselleştirme ────────────
fig, ax = plt.subplots(figsize=(14, 7), facecolor='#030c1a')
ax.set_facecolor('#061220')

# Özel yeşil-mavi renk haritası (oşinografik klorofil standardı)
chl_colors = [
    '#030c1a', '#041e2c', '#062639',
    '#083d20', '#0f6b2f',
    '#1a9a3a', '#37bc4d',
    '#6bce6b', '#a5e887',
    '#d4f5a0', '#f0fde8',
]
chl_cmap = mcolors.LinearSegmentedColormap.from_list('CHL_GREEN', chl_colors, N=256)

# Filled contour — bulutumsu yapı
cf = ax.contourf(glo, gla, chl_smooth,
                 levels=30, cmap=chl_cmap, alpha=0.88)

# Kontur çizgileri
ct = ax.contour(glo, gla, chl_vals,
                levels=[0.5, 1.0, 2.0, 4.0, 8.0],
                colors='#4ade80', linewidths=0.7, alpha=0.5)
ax.clabel(ct, fmt='%.1f mg/m³', fontsize=7, colors='#4ade80')

# Colorbar
cbar = fig.colorbar(cf, ax=ax, fraction=0.025, pad=0.01,
                    label='log(1 + Klorofil-a) mg/m³')
cbar.ax.yaxis.label.set_color('#94b8d4')
cbar.ax.tick_params(colors='#5a7a96')

# Mera noktaları
for nm, sp in SPOTS.items():
    ax.plot(sp['lon'], sp['lat'], 'o', ms=6, mfc='#fbbf24',
            mec='white', mew=0.8, alpha=0.9, zorder=5)
    ax.annotate(nm[:10], (sp['lon'], sp['lat']),
                xytext=(3, 3), textcoords='offset points',
                fontsize=6, color='#dff1ff', alpha=0.8)

# Kıyı benzeri grid çizgisi
ax.set_xlim(26.0, 30.3); ax.set_ylim(40.25, 41.55)
ax.set_xlabel('Boylam (°D)', color='#94b8d4', fontsize=10)
ax.set_ylabel('Enlem (°K)', color='#94b8d4', fontsize=10)
ax.set_title('🌿 Marmara Klorofil-a Dağılımı — NASA VIIRS ERDDAP\n'
             '(Yeşil yoğunluk = yüksek fitoplankton, balık aktivitesi)',
             color='#38bdf8', fontsize=13, pad=10)
ax.grid(True, alpha=0.2, color='#1e3a5f')

for sp in ax.spines.values(): sp.set_edgecolor('#1e3a5f')

plt.tight_layout()
plt.savefig('02_chlorophyll_map.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Grafik kaydedildi: 02_chlorophyll_map.png')

"""## 💨 7. Rüzgar Vektör Haritası (Quiver)"""

# Tüm spotlar için anlık rüzgar verisi al
from concurrent.futures import ThreadPoolExecutor

def get_current_wind(lat, lon):
    d = fetch_openmeteo(lat, lon, 'icon_eu')
    h = d.get('hourly',{})
    if not h: return None
    # Şimdiki saate en yakın değer
    now = datetime.datetime.now().strftime('%Y-%m-%dT%H:00')
    times = h.get('time',[])
    ws_list = h.get('windspeed_10m',[])
    wd_list = h.get('winddirection_10m',[])
    if not times: return None
    idx = 0
    if now in times: idx = times.index(now)
    ws = ws_list[idx] if ws_list else 0
    wd = wd_list[idx] if wd_list else 0
    return ws, wd

print('📡 Spot rüzgar verileri çekiliyor...')
wind_data = {}
with ThreadPoolExecutor(max_workers=10) as ex:
    futs = {ex.submit(get_current_wind, sp['lat'], sp['lon']): nm
            for nm, sp in SPOTS.items()}
    for fut, nm in futs.items():
        result = fut.result()
        if result:
            wind_data[nm] = {'ws': result[0], 'wd': result[1],
                              **SPOTS[nm]}
            print(f'  ✅ {nm}: {result[0]:.0f} km/h {result[1]:.0f}°')

print(f'\n{len(wind_data)} noktadan veri alındı')

# ── Rüzgar vektör haritası ────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 7), facecolor='#030c1a')
ax.set_facecolor('#040f1e')

# Koordinat ızgarası
for lat_l in np.arange(40.2, 41.8, 0.3):
    ax.axhline(lat_l, color='#0d2040', lw=0.5, alpha=0.7)
for lon_l in np.arange(26.0, 30.5, 0.5):
    ax.axvline(lon_l, color='#0d2040', lw=0.5, alpha=0.7)

# Spot vektörleri
arrow_scale = 0.0035
for nm, d in wind_data.items():
    ws, wd = d['ws'], d['wd']
    wd_rad = math.radians(wd)
    # U: doğu, V: kuzey (meteorolojik FROM konvansiyonu)
    u = -ws * math.sin(wd_rad)
    v = -ws * math.cos(wd_rad)

    # Beaufort rengini bul
    bft_thresholds = [1,6,12,20,29,39,50,62,75,89,103,118]
    bft_colors = ['#dbeafe','#93c5fd','#60a5fa','#34d399','#a3e635',
                  '#fbbf24','#fb923c','#f87171','#e11d48','#be185d','#7e22ce','#312e81','#030712']
    b = next((i for i,t in enumerate(bft_thresholds) if ws < t), 12)
    col = bft_colors[min(b,12)]

    ax.annotate('', xy=(d['lon'] + u*arrow_scale, d['lat'] + v*arrow_scale),
                xytext=(d['lon'], d['lat']),
                arrowprops=dict(arrowstyle='->', color=col, lw=2.5+b*0.2,
                                mutation_scale=18))
    ax.plot(d['lon'], d['lat'], 'o', ms=5, color=col, mec='white', mew=0.5)
    ax.annotate(f'{nm[:8]}\n{ws:.0f}km/h', (d['lon'], d['lat']),
                xytext=(4,-12), textcoords='offset points',
                fontsize=7, color='#dff1ff', alpha=0.85)

    # Kıyıya dik mi? (onshore)
    sf = d['shore_facing']
    adiff = abs(wd - sf)
    adiff = min(adiff, 360-adiff)
    if adiff <= 45:
        ax.plot(d['lon'], d['lat'], 's', ms=9, color='none',
                mec='#4ade80', mew=1.5, alpha=0.8, zorder=10)
        ax.annotate('✓ON', (d['lon'], d['lat']),
                    xytext=(4, 4), textcoords='offset points',
                    fontsize=6, color='#4ade80', fontweight='bold')

# Beaufort lejantı
bft_legend = [(0,'#dbeafe','B0-1 Hafif'),
              (2,'#60a5fa','B2-3 Seriniz'),
              (4,'#34d399','B4 Orta'),
              (5,'#fbbf24','B5-6 Taze'),
              (7,'#f87171','B7+ Sert')]
for i,(b,c,lbl) in enumerate(bft_legend):
    ax.plot([], [], 'o-', color=c, lw=2.5, ms=6, label=lbl)
ax.plot([], [], 's', ms=8, color='none', mec='#4ade80', mew=1.5,
        label='Onshore (levrek)')
ax.legend(loc='lower left', fontsize=8, framealpha=0.3,
          facecolor='#0a1628', edgecolor='#1e3a5f')

ax.set_xlim(26.0, 30.5); ax.set_ylim(40.2, 41.6)
ax.set_xlabel('Boylam', color='#94b8d4')
ax.set_ylabel('Enlem', color='#94b8d4')
ax.set_title('💨 Anlık Rüzgar Vektörleri — Marmara Denizi\n'
             '(ICON-EU 7km | yeşil kare = kıyıya dik / onshore)',
             color='#38bdf8', fontsize=13, pad=10)

for sp in ax.spines.values(): sp.set_edgecolor('#1e3a5f')
plt.tight_layout()
plt.savefig('03_wind_vectors.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Grafik kaydedildi: 03_wind_vectors.png')

"""## 📉 8. Basınç İzobar Haritası"""

# Geniş ızgara için basınç verisi
grid_lats_p = np.linspace(40.3, 41.5, 6)
grid_lons_p = np.linspace(26.0, 30.2, 9)
glo_p, gla_p = np.meshgrid(grid_lons_p, grid_lats_p)

print('📡 Basınç verileri çekiliyor...')
pres_grid = np.zeros_like(glo_p)

def get_pressure(lat, lon):
    d = fetch_openmeteo(lat, lon, 'icon_eu')
    h = d.get('hourly',{})
    if not h: return 1013.0
    pres = h.get('surface_pressure',[])
    return float(pres[0]) if pres else 1013.0

with ThreadPoolExecutor(max_workers=8) as ex:
    futs = {}
    for i in range(gla_p.shape[0]):
        for j in range(gla_p.shape[1]):
            futs[ex.submit(get_pressure, gla_p[i,j], glo_p[i,j])] = (i,j)
    for fut, (i,j) in futs.items():
        pres_grid[i,j] = fut.result()

pres_smooth = gaussian_filter(pres_grid, sigma=1.5)
print(f'✅ Basınç: {pres_smooth.min():.0f} – {pres_smooth.max():.0f} hPa')

# ── İzobar haritası ──────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 7), facecolor='#030c1a')
ax.set_facecolor('#040f1e')

# Basınç renk haritası
pres_colors = ['#7c3aed','#be185d','#ef4444','#f97316','#fbbf24',
               '#a3e635','#4ade80','#22d3ee','#818cf8']
pres_cmap = mcolors.LinearSegmentedColormap.from_list('PRESSURE', pres_colors, N=256)

# Renk doldurma
p_min = max(950, pres_smooth.min()-2)
p_max = min(1040, pres_smooth.max()+2)
cf_p = ax.contourf(glo_p, gla_p, pres_smooth,
                   levels=np.arange(p_min, p_max, 2),
                   cmap=pres_cmap, alpha=0.75)

# İzobar çizgileri — her 4 hPa
isobar_levels = np.arange(p_min, p_max, 4)
ct_p = ax.contour(glo_p, gla_p, pres_smooth,
                  levels=isobar_levels,
                  colors='white', linewidths=[2.0 if l%8==0 else 0.8 for l in isobar_levels],
                  alpha=0.7)
ax.clabel(ct_p, fmt='%d hPa', fontsize=8, colors='white', inline_spacing=4)

# Colorbar
cbar_p = fig.colorbar(cf_p, ax=ax, fraction=0.025, pad=0.01, label='Basınç (hPa)')
cbar_p.ax.yaxis.label.set_color('#94b8d4')
cbar_p.ax.tick_params(colors='#5a7a96')

# Rüzgar okları üzerine
for nm, d in wind_data.items():
    ws, wd = d['ws'], d['wd']
    wd_rad = math.radians(wd)
    u = -ws * math.sin(wd_rad) * 0.003
    v = -ws * math.cos(wd_rad) * 0.003
    ax.annotate('', xy=(d['lon']+u, d['lat']+v), xytext=(d['lon'], d['lat']),
                arrowprops=dict(arrowstyle='->', color='white', lw=1.5,
                                mutation_scale=14))
    ax.plot(d['lon'], d['lat'], 'o', ms=4, color='white', alpha=0.8)

# Düşük/Yüksek basınç merkezi
min_idx = np.unravel_index(pres_smooth.argmin(), pres_smooth.shape)
max_idx = np.unravel_index(pres_smooth.argmax(), pres_smooth.shape)
ax.text(glo_p[min_idx], gla_p[min_idx], 'L', ha='center', va='center',
        fontsize=22, fontweight='bold', color='#ef4444', alpha=0.9)
ax.text(glo_p[max_idx], gla_p[max_idx], 'H', ha='center', va='center',
        fontsize=22, fontweight='bold', color='#818cf8', alpha=0.9)

ax.set_xlim(26.0, 30.3); ax.set_ylim(40.25, 41.55)
ax.set_xlabel('Boylam (°D)', color='#94b8d4')
ax.set_ylabel('Enlem (°K)', color='#94b8d4')
ax.set_title('📉 Basınç İzobar Haritası — Marmara Denizi\n'
             '(4 hPa aralıklı konturlar | L=Alçak, H=Yüksek basınç)',
             color='#38bdf8', fontsize=13, pad=10)
ax.grid(True, alpha=0.15, color='#1e3a5f')
for sp in ax.spines.values(): sp.set_edgecolor('#1e3a5f')

plt.tight_layout()
plt.savefig('04_pressure_isobar.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Grafik kaydedildi: 04_pressure_isobar.png')

"""## 🌡️ 9. Stormglass — Oşinografik Zaman Serisi"""

# Stormglass — 7 günlük zaman serisi (merkez nokta)
# NOT: Ücretsiz plan = 10 istek/gün

if STORMGLASS_KEY and STORMGLASS_KEY != 'BURAYA_STORMGLASS_KEY_YAZ':
    now = datetime.datetime.utcnow()
    end = now + datetime.timedelta(days=7)
    try:
        r = requests.get('https://api.stormglass.io/v2/weather/point', params={
            'lat': LAT, 'lng': LON,
            'params': 'waterTemperature,currentSpeed,currentDirection,'
                      'salinity,waveHeight,seaLevel,waterOxygen',
            'start': int(now.timestamp()),
            'end':   int(end.timestamp()),
        }, headers={'Authorization': STORMGLASS_KEY}, timeout=15)

        if r.ok:
            hours = r.json().get('hours', [])
            def gv(h, key):
                src = h.get(key, {})
                for s in ['sg','noaa','icon','dwd']:
                    if s in src: return src[s]
                return None

            sg_rows = []
            for h in hours:
                sg_rows.append({
                    'time':       pd.to_datetime(h['time']),
                    'sst':        gv(h,'waterTemperature'),
                    'salinity':   gv(h,'salinity'),
                    'current_spd':gv(h,'currentSpeed'),
                    'sea_level':  gv(h,'seaLevel'),
                    'oxygen':     gv(h,'waterOxygen'),
                })
            sg_df = pd.DataFrame(sg_rows)
            print(f'✅ Stormglass: {len(sg_df)} saat veri')
            print(sg_df.describe().round(2))
        else:
            print(f'⚠️ Stormglass hata: {r.status_code}')
            sg_df = pd.DataFrame()
    except Exception as e:
        print(f'❌ Stormglass: {e}')
        sg_df = pd.DataFrame()
else:
    print('⚠️ Stormglass API key tanımlı değil')
    print('   Ayarlamak için: STORMGLASS_KEY değişkenini güncelle')
    print('   Ücretsiz kayıt: https://stormglass.io')
    # Demo veri
    times = pd.date_range(start='now', periods=168, freq='1h')
    sg_df = pd.DataFrame({
        'time': times,
        'sst': 14 + 2*np.sin(np.linspace(0, 4*np.pi, 168)) + np.random.normal(0,.3,168),
        'salinity': 18 + np.random.normal(0,.2,168),
        'current_spd': np.abs(np.random.normal(0.15, 0.08, 168)),
        'sea_level': np.random.normal(0, 0.15, 168),
    })
    print('   ℹ️ Demo verisi oluşturuldu')

if not sg_df.empty:
    fig = make_subplots(
        rows=3, cols=2,
        subplot_titles=[
            '🌡️ Su Sıcaklığı (SST)', '🧂 Tuzluluk',
            '🌀 Akıntı Hızı (m/s)', '📏 Deniz Seviyesi (m)',
            '💧 Su Oksijeni (ml/L)' if 'oxygen' in sg_df.columns else '📈 Trend', '📊 Dağılım'
        ],
        shared_xaxes=False
    )

    plot_style = dict(line=dict(width=2), mode='lines')

    fig.add_trace(go.Scatter(x=sg_df['time'], y=sg_df['sst'],
                             name='SST', line=dict(color='#f87171', width=2.5),
                             fill='tozeroy', fillcolor='rgba(248,113,113,0.1)'),
                  row=1, col=1)
    fig.add_trace(go.Scatter(x=sg_df['time'], y=sg_df['salinity'],
                             name='Tuzluluk', line=dict(color='#38bdf8', width=2)),
                  row=1, col=2)
    if 'current_spd' in sg_df:
        fig.add_trace(go.Scatter(x=sg_df['time'], y=sg_df['current_spd'],
                                 name='Akıntı', line=dict(color='#2dd4bf', width=2)),
                      row=2, col=1)
    if 'sea_level' in sg_df:
        fig.add_trace(go.Scatter(x=sg_df['time'], y=sg_df['sea_level'],
                                 name='Deniz Seviyesi', line=dict(color='#a78bfa', width=2),
                                 fill='tozeroy', fillcolor='rgba(167,139,250,0.1)'),
                      row=2, col=2)
    if 'oxygen' in sg_df.columns and sg_df['oxygen'].notna().any():
        fig.add_trace(go.Scatter(x=sg_df['time'], y=sg_df['oxygen'],
                                 name='Oksijen', line=dict(color='#4ade80', width=2)),
                      row=3, col=1)

    # SST histogram
    fig.add_trace(go.Histogram(x=sg_df['sst'].dropna(), name='SST Dağılım',
                               marker_color='#f87171', opacity=0.7, nbinsx=20),
                  row=3, col=2)

    fig.update_layout(
        height=700, title_text='🌊 Stormglass Oşinografik Veri Paneli',
        title_font=dict(size=16, color='#38bdf8'),
        paper_bgcolor='#030c1a', plot_bgcolor='#0d1e35',
        font=dict(color='#dff1ff', size=11),
        showlegend=False,
    )
    fig.update_xaxes(gridcolor='#1e3a5f', linecolor='#1e3a5f')
    fig.update_yaxes(gridcolor='#1e3a5f', linecolor='#1e3a5f')
    fig.show()
    fig.write_html('05_stormglass_oceanographic.html')
    print('📊 Grafik kaydedildi: 05_stormglass_oceanographic.html')

"""## 🎣 10. Onshore Rüzgar Analizi — Levrek Skoru"""

# 7 günlük en iyi levrek saatlerini bul
def adiff(a, b):
    d = abs(a-b); return min(d, 360-d)

# Tekirdağ örneği (lodos kıyısı, shore_facing=135)
spot_name = 'Tekirdağ'
spot      = SPOTS[spot_name]

d_trd = fetch_openmeteo(spot['lat'], spot['lon'], 'icon_eu')
h_trd = d_trd.get('hourly', {})

if h_trd:
    times_t = pd.to_datetime(h_trd['time'])
    ws_raw  = h_trd['windspeed_10m']
    wd_raw  = h_trd['winddirection_10m']
    wg_raw  = h_trd.get('windgusts_10m', ws_raw)
    pr_raw  = h_trd.get('surface_pressure', [1013]*len(times_t))

    # DataFrame oluşturup None değerleri temizle
    df_hourly = pd.DataFrame({
        'time': times_t,
        'ws': ws_raw,
        'wd': wd_raw,
        'wg': wg_raw,
        'pressure': pr_raw
    }).dropna()

    if not df_hourly.empty:
        times_t = df_hourly['time'].values
        ws_t    = df_hourly['ws'].values
        wd_t    = df_hourly['wd'].values
        wg_t    = df_hourly['wg'].values
        pr_t    = df_hourly['pressure'].values

        sf = spot['shore_facing']
        is_on   = [adiff(wd_t[i], sf) <= 45  for i in range(len(wd_t))]
        is_side = [45 < adiff(wd_t[i], sf) <= 90 for i in range(len(wd_t))]

        # Skor hesabı
        scores = []
        for i in range(len(times_t)):
            s = 0.0
            if is_on[i]:   s += 3.5
            elif is_side[i]: s += 1.5
            if 15 <= ws_t[i] <= 40: s += 2.0
            elif ws_t[i] > 40: s += 0.5
            # Basınç bonusu
            if pr_t[i] < 1005: s += 1.5
            elif pr_t[i] < 1010: s += 1.0
            scores.append(min(10.0, s))

        df_trd = pd.DataFrame({
            'time': times_t, 'ws': ws_t, 'wd': wd_t,
            'is_on': is_on, 'pressure': pr_t, 'score': scores
        })

        best = df_trd.nlargest(5, 'score')
        print(f'🎣 {spot_name} — En İyi 5 Levrek Saati (7 gün):')
        print(best[['time','ws','wd','is_on','pressure','score']].to_string(index=False))
    else:
        print(f'⚠️ {spot_name} için yeterli rüzgar verisi bulunamadı.')
else:
    print(f'⚠️ {spot_name} için Open-Meteo verisi çekilemedi.')

# ── Skor görselleştirme ─────────────────────────────────────
if 'df_trd' in dir():
    fig, ax = plt.subplots(figsize=(16, 6), facecolor='#030c1a')
    ax.set_facecolor('#040f1e')

    # Skor barı
    colors = ['#4ade80' if s>=7 else '#fbbf24' if s>=4.5 else '#f87171'
              for s in df_trd['score']]
    bars = ax.bar(df_trd['time'], df_trd['score'], color=colors,
                  alpha=0.8, width=0.04, label='Levrek Skoru')

    # Rüzgar hızı (ikincil eksen)
    ax2 = ax.twinx()
    ax2.plot(df_trd['time'], df_trd['ws'], color='#38bdf8', lw=2,
             alpha=0.8, label='Rüzgar (km/h)')
    ax2.fill_between(df_trd['time'], df_trd['ws'], 0, alpha=0.12, color='#38bdf8')
    ax2.set_ylabel('Rüzgar km/h', color='#38bdf8')
    ax2.tick_params(colors='#38bdf8')

    # Onshore markerları
    on_times = df_trd[df_trd['is_on']]['time']
    ax.scatter(on_times, [9.5]*len(on_times), marker='^', s=60,
               color='#4ade80', alpha=0.8, zorder=5, label='Onshore ✓')

    ax.axhline(7, color='#4ade80', ls='--', lw=1, alpha=0.5)
    ax.axhline(4.5, color='#fbbf24', ls='--', lw=1, alpha=0.5)
    ax.set_ylim(0, 10.5)
    ax.set_ylabel('Levrek Skoru (/10)', color='#dff1ff')
    ax.set_title(f'🎣 {spot_name} — 7 Günlük Levrek Fırsatı (ICON-EU 7km)\n'
                 '🟢 ≥7 Mükemmel | 🟡 4.5-7 İyi | 🔴 <4.5 Zayıf | ▲ Onshore',
                 color='#38bdf8', fontsize=13, pad=10)
    ax.xaxis.set_major_formatter(plt.matplotlib.dates.DateFormatter('%d/%m %H:00'))
    plt.xticks(rotation=35, ha='right', fontsize=8)
    ax.grid(True, alpha=0.2, color='#1e3a5f')
    lines1, labels1 = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines1+lines2, labels1+labels2, loc='upper right',
              fontsize=9, framealpha=0.3, facecolor='#0a1628')
    for sp in ax.spines.values(): sp.set_edgecolor('#1e3a5f')
    plt.tight_layout()
    plt.savefig('06_levrek_score.png', dpi=150, bbox_inches='tight')
    plt.show()
    print('📊 Grafik kaydedildi: 06_levrek_score.png')

"""## ✅ Özet — Kaydedilen Dosyalar

| Dosya | İçerik |
|-------|--------|
| `01_wind_wave_analysis.png` | 4 model karşılaştırması, dalga, basınç |
| `02_chlorophyll_map.png` | Klorofil uzamsal haritası (yeşil bulut) |
| `03_wind_vectors.png` | Rüzgar vektör haritası, onshore tespiti |
| `04_pressure_isobar.png` | İzobar basınç haritası, L/H merkezler |
| `05_stormglass_oceanographic.html` | Oşinografik panel (SST, tuzluluk, oksijen) |
| `06_levrek_score.png` | 7 günlük levrek fırsatı skoru |

**Google Drive'a kaydetmek için:**
```python
from google.colab import drive
drive.mount('/content/drive')
import shutil
for f in ['01_wind_wave_analysis.png', '02_chlorophyll_map.png',
          '03_wind_vectors.png', '04_pressure_isobar.png',
          '06_levrek_score.png']:
    shutil.copy(f, f'/content/drive/MyDrive/{f}')
```
"""